name: "deploy-container-to-registry"
description: "Deploys container to GithubContainer and DockerHub"
inputs:
  docker-username:
    required: true
    description: "The secret key stored to deploy to docker hub"
  docker-password:
    required: true
    description: "The secret password to deploy to docker hub"
  project-name:
    required: true
    description: "Project name to publish image"
  service-name:
    required: true
    description: "Service name of image that is deployed"
  dockerfile-path:
    required: true
    description: "Path + Name of Dockerfile used to deploy container"
  github-actor:
    required: true
    description: "Username for github container"
  github-token:
    required: true
    description: "password for github container"
  github-repository:
    required: true
    description: "Name of the github repository"

runs:
  using: "composite"
  steps:
    - name: "Log in to Docker Hub"
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: "Log in to the Container registry"
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ inputs.github-actor }}
        password: ${{ inputs.github-token }}

    - name: "Extract metadata (tags, labels) for Docker "
      id: meta
      uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
      with:
        images: |
          ${{ inputs.docker-username }}/${{ inputs.project-name }}-${{ inputs.service-name }}
          ghcr.io/${{ inputs.github-repository }}-${{ inputs.service-name }}

    - name: Build and push Docker image - client
      uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
      with:
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
